rdsText  = ""
source = ""
freq = ""
stationMem = ""
modType = ""
radioBand = ""
volume = 0
isVolumeChanging = False
isVolumeStillChanging = False
radioPower = False
isLRBal = False
showAudioMenu = False
isRFBal = False
isBass = False
isTreble = False
isLoudness = False
isAutoVol = False
isEQPreset = False
lrValue = "0"
rfValue = "0"
bassValue = "0"
trebleValue = "0"
loudValue = "0"
autoVolValue = "0"
eqPresetValue = ""
srcImage = "aux_cable.png"
trackAll = 0
discType = "Audio CD"
cdCurrentTrack = 0
currentTrackTime = "0"
isMenuOpen = False
menuItem = "None"
showMainMenu = False
current_time_USB = "00:00"
usbTrackName = ["Artist","Track Name"]
cdTrackDetails = ["Artist", "Track Name"]
trackList = [" ", " ", " ", " "]
showList = False
trackListSel = [False, False, False, False]
tripInfo = ["--", "pepe", "--"]
darkMode = False
tripMode = 0
tripImage = ["trip_distance.png", "trip_fuel.png", "trip_gasstation.png"]
